{
 "title": "Matches",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": { "query": "label_values(source)" } },
   { "name": "product", "label": "Product", "query": { "query": "label_values(product)" } },
   { "name": "indicator", "label": "Indicator", "query": { "query": "label_values(indicator)" } },
   { "name": "candle", "label": "Candle Period", "query": { "query": "label_values(candle_period)" } },
   {
    "name": "ma_indicators",
    "query": "bollingerbands, chaikinoscillator, chandekrollstop, commoditychannelindex, donchianchannel, eldersforceindex, envelopes, fishertransform, hullmovingaverage, ichimokucloud, kaufman, keltnetchannel, klingrvolumeoscillator, paraboliscar, pricechannelstrategy, trix"
   }
  ]
 },
 "panels": [
  {
   "title": "Candle",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tradehook_open{candle_period=\"$candle\", product=\"$product\", source=\"$source\"}",
     "legendFormat": "open"
    },
    {
     "expr": "tradehook_high{candle_period=\"$candle\", product=\"$product\", source=\"$source\"}",
     "legendFormat": "high"
    },
    {
     "expr": "tradehook_low{candle_period=\"$candle\", product=\"$product\", source=\"$source\"}",
     "legendFormat": "low"
    },
    {
     "expr": "tradehook_close{candle_period=\"$candle\", product=\"$product\", source=\"$source\"}",
     "legendFormat": "close"
    },
    {
     "expr": "tradehook_volume{candle_period=\"$candle\", product=\"$product\", source=\"$source\"}",
     "legendFormat": "volume"
    }
   ]
  },
  {
   "title": "Task count",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(actor_name) (delta(tradehook_task_count[${candle}s]))",
     "legendFormat": "{{actor_name}}"
    }
   ]
  },
  {
   "title": "Flush duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(actor_name) (tradehook_flush_duration)",
     "legendFormat": "{{actor_name}}"
    }
   ]
  },
  {
   "title": "Handle",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by(actor_name) (rate(tradehook_handle_success[$__rate_interval]))",
     "legendFormat": "{{actor_name}}"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "tradehook_volume{candle_period=\"$candle\", product=\"$product\", source=\"$source\"}",
     "legendFormat": "volume"
    }
   ]
  },
  {
   "title": "Indicator values",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "tradehook_indicator_value{indicator=~\"$indicator\", product=~\"$product\", candle_period=\"$candle\", source=\"$source\"}",
     "legendFormat": "{{indicator}}_{{value}}"
    }
   ]
  },
  {
   "title": "Indicator signals",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "tradehook_indicator_signal{indicator=~\"$indicator\", product=~\"$product\", candle_period=\"$candle\", source=\"$source\"}",
     "legendFormat": "{{indicator}}_{{signal}}"
    }
   ]
  }
 ]
}